// swift-tools-version: 6.0
import PackageDescription

let package = Package(
    name: "UtataneModules",
    platforms: [.macOS(.v14)],
    products: [.library(name: "misaka", type: .dynamic, targets: ["MisakaModule"]),
        .library(name: "niseshiori", type: .dynamic, targets: ["NiseShioriModule"]),
        .library(name: "ese-shiori", type: .dynamic, targets: ["EseShioriModule"]),
        .library(name: "yuhna", type: .dynamic, targets: ["YuhnaModule"]),
        .library(name: "hisui", type: .dynamic, targets: ["HisuiModule"]),
        .library(name: "shino", type: .dynamic, targets: ["ShinoModule"]),
        .library(name: "akari", type: .dynamic, targets: ["AkariModule"]),
        .library(name: "kawari", type: .dynamic, targets: ["KawariModule"]),
        .library(name: "saori_cpuid", type: .dynamic, targets: ["SaoriCPUIDModule"]),
        .library(name: "kenonoke", type: .dynamic, targets: ["KenonokeModule"]),
        .library(name: "textcopy2", type: .dynamic, targets: ["TextCopyModule"]),
        .library(name: "mciaudior", type: .dynamic, targets: ["MciAudioModule"]),
        .library(name: "wmove", type: .dynamic, targets: ["WmoveModule"])],
    targets: [
        .target(name: "CMisakaHostBridge", path: "bridge", exclude: ["tests"], sources: ["anchor.c"], publicHeadersPath: "include"),
        .target(name: "ModuleProtocol"),
        .target(name: "LegacyTextCodec", path: "Sources/LegacyTextCodec", publicHeadersPath: "include", linkerSettings: [.linkedLibrary("iconv")]),
        .target(name: "LegacyText", dependencies: ["LegacyTextCodec"]),
        .target(name: "NiseShioriCore", dependencies: ["ModuleProtocol", "LegacyText"]),
        .target(name: "NiseShioriModule", dependencies: ["NiseShioriCore", "ModuleProtocol", "LegacyText"]),
        .testTarget(name: "NiseShioriCoreTests", dependencies: ["NiseShioriCore", "ModuleProtocol"]),
        .target(name: "EseShioriCore", dependencies: ["ModuleProtocol", "LegacyText"]),
        .target(name: "EseShioriModule", dependencies: ["EseShioriCore", "ModuleProtocol", "LegacyText"]),
        .testTarget(name: "EseShioriCoreTests", dependencies: ["EseShioriCore", "ModuleProtocol"]),
        .target(name: "YuhnaCore", dependencies: ["ModuleProtocol", "LegacyText"]),
        .target(name: "YuhnaModule", dependencies: ["YuhnaCore", "ModuleProtocol", "LegacyText"]),
        .testTarget(name: "YuhnaCoreTests", dependencies: ["YuhnaCore", "ModuleProtocol"]),
        .target(name: "HisuiCore", dependencies: ["ModuleProtocol", "LegacyText"]),
        .target(name: "HisuiModule", dependencies: ["HisuiCore", "ModuleProtocol", "LegacyText"]),
        .testTarget(name: "HisuiCoreTests", dependencies: ["HisuiCore", "ModuleProtocol"]),
        .target(name: "SaoriClient", dependencies: ["LegacyText"]),
        .target(name: "ShinoCore", dependencies: ["ModuleProtocol", "LegacyText", "SaoriClient"]),
        .target(name: "ShinoModule", dependencies: ["ShinoCore", "ModuleProtocol", "LegacyText"]),
        .testTarget(name: "ShinoCoreTests", dependencies: ["ShinoCore", "ModuleProtocol", "SaoriClient"]),
        .target(name: "AkariCore", dependencies: ["ModuleProtocol", "LegacyText", "SaoriClient"]),
        .target(name: "AkariModule", dependencies: ["AkariCore", "ModuleProtocol", "LegacyText"]),
        .testTarget(name: "AkariCoreTests", dependencies: ["AkariCore", "ModuleProtocol"]),
        .target(name: "CKawariNative", path: "Sources/CKawariModule", sources: [
            "KawariBridge.cpp",
            "Vendor/KAWARI/build/src/shiori/kawari_shiori.cpp",
            "Vendor/KAWARI/build/src/libkawari/kawari_engine.cpp",
            "Vendor/KAWARI/build/src/libkawari/kawari_ns.cpp",
            "Vendor/KAWARI/build/src/libkawari/kawari_dict.cpp",
            "Vendor/KAWARI/build/src/libkawari/kawari_code.cpp",
            "Vendor/KAWARI/build/src/libkawari/kawari_codeset.cpp",
            "Vendor/KAWARI/build/src/libkawari/kawari_codeexpr.cpp",
            "Vendor/KAWARI/build/src/libkawari/kawari_codekis.cpp",
            "Vendor/KAWARI/build/src/libkawari/kawari_vm.cpp",
            "Vendor/KAWARI/build/src/libkawari/kawari_lexer.cpp",
            "Vendor/KAWARI/build/src/libkawari/kawari_compiler.cpp",
            "Vendor/KAWARI/build/src/libkawari/kawari_log.cpp",
            "Vendor/KAWARI/build/src/libkawari/kawari_rc.cpp",
            "Vendor/KAWARI/build/src/misc/misc.cpp",
            "Vendor/KAWARI/build/src/misc/mt19937ar.cpp",
            "Vendor/KAWARI/build/src/misc/l10n.cpp",
            "Vendor/KAWARI/build/src/misc/phttp.cpp",
            "Vendor/KAWARI/build/src/saori/saori.cpp",
            "Vendor/KAWARI/build/src/saori/saori_module.cpp",
            "Vendor/KAWARI/build/src/saori/saori_unique.cpp",
            "Vendor/KAWARI/build/src/kis/kis_echo.cpp",
            "Vendor/KAWARI/build/src/kis/kis_dict.cpp",
            "Vendor/KAWARI/build/src/kis/kis_date.cpp",
            "Vendor/KAWARI/build/src/kis/kis_counter.cpp",
            "Vendor/KAWARI/build/src/kis/kis_file.cpp",
            "Vendor/KAWARI/build/src/kis/kis_escape.cpp",
            "Vendor/KAWARI/build/src/kis/kis_urllist.cpp",
            "Vendor/KAWARI/build/src/kis/kis_substitute.cpp",
            "Vendor/KAWARI/build/src/kis/kis_split.cpp",
            "Vendor/KAWARI/build/src/kis/kis_communicate.cpp",
            "Vendor/KAWARI/build/src/kis/kis_xargs.cpp",
            "Vendor/KAWARI/build/src/kis/kis_string.cpp",
            "Vendor/KAWARI/build/src/kis/kis_help.cpp",
            "Vendor/KAWARI/build/src/kis/kis_saori.cpp",
            "Vendor/KAWARI/build/src/kis/kis_system.cpp",
            "Vendor/KAWARI/build/src/libkawari/kawari_crypt.cpp",
            "Vendor/KAWARI/build/src/misc/base64.cpp"
        ], publicHeadersPath: "Include", cxxSettings: [
            .headerSearchPath("Vendor/KAWARI/build/src"),
            .unsafeFlags(["-Wno-writable-strings", "-Wno-reserved-user-defined-literal"])
        ]),
        .target(name: "KawariCore", dependencies: ["CKawariNative", "ModuleProtocol", "SaoriClient"]),
        .target(name: "KawariModule", dependencies: ["KawariCore", "ModuleProtocol", "LegacyText"]),
        .testTarget(name: "KawariCoreTests", dependencies: ["KawariCore", "ModuleProtocol"]),
        .target(name: "SaoriCore"),
        .target(name: "SaoriRuntime", dependencies: ["SaoriCore"]),
        .target(name: "SaoriCPUIDModule", dependencies: ["SaoriRuntime"]),
        .target(name: "KenonokeModule", dependencies: ["SaoriRuntime"]),
        .target(name: "TextCopyModule", dependencies: ["SaoriRuntime"]),
        .target(name: "MciAudioModule", dependencies: ["SaoriRuntime"]),
        .target(name: "WmoveModule", dependencies: ["SaoriRuntime"]),
        .testTarget(name: "SaoriTests", dependencies: ["SaoriCore", "SaoriRuntime"]),
        .target(name: "MisakaCore", dependencies: ["ModuleProtocol"]),
        .target(name: "MisakaModule", dependencies: ["MisakaCore", "ModuleProtocol", "CMisakaHostBridge"]),
        .testTarget(name: "MisakaCoreTests", dependencies: ["MisakaCore", "ModuleProtocol"])
    ]
)
